### PR TITLE
Add WPStackPro to 💻 Code

### PR DESCRIPTION
**Pull request by ashfame**

### CODE REVIEW

**Comment by pugson** [comment]
@ashfame Hmm, there's no way to start using this right now? Or am I missing something?

cc @marckohlbrugge

**Comment by ashfame** [comment]
@pugson Yeah! It's in too early-stage, as in, I have it running 3 of my products, but except documentation page of its features, I don't have its main landing page setup.

The day anyone gets ready to buy is when I am setting up the page, unless Marc requires me to have that up before this gets included in the resource list, then I will do it today.

**Comment by pugson** [comment]
I would vote for products that can be used right away without any additional steps required.

**Comment by marckohlbrugge** [comment]
Yeah I agree with @pugson. The goal of this list is to help makers save time by providing the best resources they can use right now.

**Review by pugson — CHANGES_REQUESTED** [review]
Please make the product easily accessible to everyone before being added to the list. The less friction to get it working for the makers, the better 😎️

**Review by marckohlbrugge — DISMISSED** [review]
let's wait until it's publicly available for makers to use. would you mind sending a PR when that happens? thanks!

**Comment by ashfame** [comment]
@pugson @marckohlbrugge Alright! I know what I am doing today.

**Comment by ashfame** [comment]
@pugson @marckohlbrugge As promised, I am now live - https://wpstackpro.com/

Can you approve now? Thanks!

**Review by pugson — APPROVED** [review]

**Comment by pugson** [comment]
GitHub's inline conflict resolver is confusing lol. Sorry for the mess.

**Pull request merged**
